name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: sudo apt-get install -y wget && mkdir extern/ && mkdir build/
    - name: Install boost library
      run: sudo apt-get install -y libboost-all-dev
    - name: Install googletest library
      run: cd extern/ && git clone https://github.com/google/googletest
    - name: Install libtorch
      run: cd extern/ && wget --quiet https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip && unzip libtorch-shared-with-deps-latest.zip
    - name: Generate build files
      run: cd build/ && cmake -DCMAKE_PREFIX_PATH=`realpath ../extern/libtorch/` ..
    - name: Build project
      run: cd build/ && make -j 8
    - name: Run executable
      run: build/aithena version
    - name: Run tests
      run: cd build/ && make test
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cpplint
        run: sudo pip install cpplint
      - name: Lint
        run: cpplint --recursive aithena/
